#!/bin/bash

PLATFORM=$1

if [[ "${PLATFORM}" == "" ]]; then
  echo "Usage: $0 <platform>"
  echo "  Where platform can be modduo[-static], modduox[-static], moddwarf or x86_64"
  exit 1
fi

# Some of the plugins have build problems, skipping them
blacklist=$(cat ./blacklist)

for pluginpath in ./plugins/package/*; do
    plugin=${pluginpath##*/}
    echo "Building $plugin"
    if [[ "$blacklist" == *"$plugin"* ]]; then
        echo "Plugin $plugin is in black list and will be skipped"
    else
        ./build $PLATFORM $plugin &>/dev/null
    fi 
done
